import type { Metadata } from "next";
import { Caveat, Geist, Geist_Mono, Poppins, Space_Grotesk } from "next/font/google";
import "./globals.css";
import SmoothScroll from "../Helpers/SmoothScroll";
import Navbar from "../Components/Navbar";
import { CustomCursor } from "../Components/CustomCursor";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
 
const caveat = Caveat({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-caveat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.className} ${caveat.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-[#0b0b0c] flex flex-col">
        <SmoothScroll>
          {/* <Navbar /> */}
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
